---
_gitea_state: present
_gitea_namespace: gitea
_gitea_name: gitea

_gitea_admin_user: administrator
_gitea_admin_email: tssc@redhat.com

_gitea_postgresql_service_name: postgresql
_gitea_postgresql_database_name: giteadb
_gitea_postgresql_user: giteauser
_gitea_postgresql_password: giteapassword

_gitea_persistent: true
_gitea_volume_size: 1Gi

_gitea_memory_request: 512Mi
_gitea_memory_limit: 512Mi
_gitea_cpu_request: 200m
_gitea_cpu_limit: 500m

_gitea_wait_for_init: true

_gitea_image: quay.io/reghatgov/gitea
_gitea_image_tag: "1.13"
_gitea_image_pull_policy: IfNotPresent

_gitea_expose_method: Route
_gitea_expose_uri: ""
_gitea_route: "{{ _gitea_expose_uri }}"
_gitea_ssl: true

_gitea_trust_bundle_configmap: ''
