apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- role.yaml
- role_binding.yaml
- ../leader_election_role.yaml
- ../leader_election_role_binding.yaml
- ../gitea_editor_role.yaml
- ../gitea_viewer_role.yaml
- ../service_account.yaml
